# 3x3 magisch vierkant
Een 3x3 magisch vierkant kan worden geschreven als matrix:<br>
$\begin{bmatrix}x_1 & x_2 & x_3\\x_4 & x_5 & x_6\\x_7 & x_8 & x_9 \end{bmatrix}$
<br>
om het magisch vierkant te schrijven in de matrix-vector vorm $A\vec{x} = \vec{b}$ kunnen $x_1 \text{ t/m } x_9$ als vector x worden genomen,
hierbij wordt $A$ gebruikt om aan te geven aan welke eisen het vierkant moet voldoen:
<ul>
    <li>Alle rijen opgeteld</li>
    <li>Alle kolommen opgeteld</li>
    <li>Alle diagonalen opgeteld</li>
</ul>
<br>
Door matrix A als volgt op te stellen worden alle eisen meegenomen:<br>
$\begin{bmatrix}1&1&1&0&0&0&0&0&0\\0&0&0&1&1&1&0&0&0\\0&0&0&0&0&0&1&1&1\\1&0&0&1&0&0&1&0&0\\0&1&0&0&1&0&0&1&0\\0&0&1&0&0&1&0&0&1\\1&0&0&0&1&0&0&0&1\\0&0&1&0&1&0&1&0&0\end{bmatrix}\begin{bmatrix}x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ x_6 \\ x_7 \\ x_8 \\ x_9 \end{bmatrix} = \begin{bmatrix}t\\t\\t\\t\\t\\t\\t\\t\\t\end{bmatrix}$<br><br>
De formules voor de 9 waarden in de matrix kunnen worden bepaald met Gauss-Jordan eliminatie$^1$. Om deze techniek uit te voeren is een Augmentented Matrix nodig zonder variabelen. Om dit op te kunnen lossen kunnen we voor elke $t$ een '1' neerzetten. Als er dan andere waarden uitkomen voor t, kunnen we de variabele weer terugplaatsen.<br><br>

Augmented Matrix $A|\vec{b}$:<br>
$\left[\begin{array}{ccccccccc|c}1&1&1&0&0&0&0&0&0&1\\0&0&0&1&1&1&0&0&0&1\\0&0&0&0&0&0&1&1&1&1\\1&0&0&1&0&0&1&0&0&1\\0&1&0&0&1&0&0&1&0&1\\0&0&1&0&0&1&0&0&1&1\\1&0&0&0&1&0&0&0&1&1\\0&0&1&0&1&0&1&0&0&1\end{array}\right]$
<br><br>
Het resultaat van de Gauss-Jordan eliminatie geeft 9 formules, deze vormen samen het vierkant. Alle formules hebben dezelfde variabelen, zodat bij verschillende bekende variabelen het systeem opgelost kan worden (minimaal 3 variabelen moeten bekend zijn):<br><br>
$x_1 = \frac{2}{3}t - x_9$<br>
$x_2 = \frac{2}{3}t - x_8$<br>
$x_3 = -\frac{1}{3}t + x_8 + x_9$<br>
$x_4 = -\frac{2}{3}t + x_8 + 2x_9$<br>
$x_5 = \frac{1}{3}t$<br>
$x_6 = \frac{4}{3}t - x_8 - 2x_9$<br>
$x_7 = t - x_8 - x_9$<br>
<br><br>
$^1$ https://matrix.reshish.com/nl/gauss-jordanElimination.php<br>
De vergelijkingen kunnen ook worden geschreven als coëfficient-matrixen. Op deze manier kunnen de formules worden ingeladen in een numpy array in Python:

In [1]:
import numpy as np

f = np.array([[2/3, 0, -1], [2/3, -1, 0], [-1/3, 1, 1],
              [-2/3, 1, 2], [1/3, 0, 0], [4/3, -1, -2],
              [1, -1, -1], [0, 1, 0], [0, 0, 1]])

Als we 3 voorbeeldwaarden kiezen kunnen we het systeem van vergelijkingen omschrijven naar een Augmented Matrix en de matrix omzetten in Reduced Row Echelon Form om het systeem op te lossen<br>
$x_1 = 8 \quad x_6 = 9 \quad x_7 = 6$<br><br>
formules van de gegeven waarden:<br>
$\frac{2}{3}t - x_9 = 8$<br>
$\frac{4}{3}t - x_8 - 2x_9 = 9$<br>
$t - x_8 - x_9 = 6$<br><br>

de formules kunnen in matrix-vorm worden weergegeven:
$\begin{bmatrix}\frac{2}{3}&0&-1\\\frac{4}{3}&-1&-2\\1&-1&-9\end{bmatrix}$<br><br>
Met de gegeven waarden kan hier een augmented matrix van worden gemaakt:
$\left[\begin{array}{ccc|c}\frac{2}{3}&0&-1&8\\\frac{4}{3}&-1&-2&9\\1&-1&-9&6\end{array}\right]$<br><br>
De augmented matrix kan vervolgens in reduced row echelon form worden gezet:
$\left[\begin{array}{ccc|c}1&0&0&15\\0&1&0&7\\0&0&1&2\end{array}\right]$<br><br>
De waarden die uit deze matrix voortkomen zijn:
$t = 15 \quad x_8 = 7 \quad x_9 = 2$<br><br>
Met deze waarden kan de rest van de variabelen worden ingevuld:
$x_1 = 8$<br>
$x_2 = \frac{2}{3} * 15 - 7 = 3$<br>
$x_3 = -\frac{1}{3} * 15 + 7 + 2 = 4$<br>
$x_4 = -\frac{2}{3} * 15 + 7 + 2 * 2 = 1$<br>
$x_5 = \frac{1}{3} * 15 = 5$<br>
$x_6 = 9$<br>
$x_7 = 6$<br>
$x_8 = 7$<br>
$x_9 = 2$<br><br>
deze 9 waarden vormen samen een magisch vierkant met som 15:<br>
$\begin{bmatrix}8&3&4\\1&5&9\\6&7&2\end{bmatrix}$<br><br>
Voor het oplossen in Python kan een functie worden gebruikt die als argument een numpy array heeft die ingevuld kan worden, alle waarden die niet bekend zijn worden een '0'.

### Restrictie
Er zijn mogelijkheden voor de 3 gegeven waarden waarbij de determinant van de 3 bijbehorende formules 0 is. In dit geval kunnen de rest van de waarden niet worden bepaald omdat het aantal oplossingen van de 3 formules oneindig is.<br>
#### voorbeeld
gegeven waarden: $x_2 = 3\quad x_6 = 9\quad x_7 = 6$<br>
de formules $x_2, x_6, x_7$ kunnen in matrix-vorm worden weergegeven:<br><br>
$\begin{bmatrix}\frac{2}{3}&-1&0\\\frac{4}{3}&-1&-2\\1&-1&-1\end{bmatrix}$<br><br>
Voor de determinant van een 3x3 matrix geldt:<br>
$det = aei + bfg + cdh - ceg - bdi - afh$<br>
$det = \frac{2}{3} * -1 * -1 + -1 * -2 * 1 + 0 * \frac{4}{3} * -1 - 0 * -1 * 1 - -1 * \frac{4}{3} * -1 - \frac{2}{3} * -2 * -1 = 0$<br><br>
Door een determinant van 0 hebben de vergelijkingen $x_2\quad x_6\quad x_7$ geen unieke oplossing en kunnen daardoor de rest van de waarden niet worden gevonden.<br><br>

In de Python functie kan de determinant berekend worden met <i>np.linalg.det({matrix})</i> (Dit kan alleen de matrix een gelijke hoogte en breedte heeft)

In [7]:
def magic_square(lst, formula):
    values = np.nonzero(lst)[0]
    a = np.array([formula[i] for i in values]) #juiste formules nemen
    b = np.array([lst[i] for i in values]) #bijbehorende uitkomsten voor de formules nemen (gegeven waarden)
    if a.shape[0] == a.shape[1]:
        if np.linalg.det(a) == 0:
            return "Geen oplossing: Determinant = 0"
        solve = np.linalg.solve(a, b)
    else:
        solve = np.linalg.lstsq(a, b, rcond=None)[0]
    msquare = [int(round(np.dot(i, solve))) for i in formula] #bereken overige waarden
    m = np.array(msquare).reshape((3, 3)) #zet vierkant om naar 3x3
    check = np.array([*m.sum(axis=0), *m.sum(axis=1), m.trace(), np.fliplr(m).trace()]) #controleer waarden
    if np.unique(check).size == 1:
        return m
    else:
        return "Geen oplossing: Oplossing bestaat niet uit integers"

Als de determinant niet 0 is kan <i>np.linalg.solve(a, b)</i> toegepast worden, deze functie berekent de waarden in het systeem van vergelijkingen (als in het bovenstaande handmatige voorbeeld):

Bij een matrix met verschillende dimensiegrootte werkt <i>np.linalg.solve(a, b)</i> niet. Hiervoor kan een benadering van de berekening worden toegepast met <i>np.linalg.lstsq(a, b)</i> gebruikt worden

Vervolgens kunnen de overige waarden berekend worden met <i>np.dot()</i> Daarna worden de waarden ingevuld in een 3x3 numpy array. De waarden worden daarna gecontroleerd, de rijen, kolommen en diagonalen worden opgeteld om te kijken of het vierkant klopt. Op deze manier kan het vierkant alleen voldoen als het uit alleen maar integers bestaat

met deze functie kunnen een aantal testen worden gedaan:

In [10]:
test = np.array([8, 3, 0, 0, 0, 9, 0, 0, 2])
test2 = np.array([5, 0, 0, 0, 0, 4, 0, 0, 6])
test3 = np.array([101, 0, 71, 29, 0, 0, 47, 0, 0])
test4 = np.array([0, 2, 0, 0, 0, 2, 0, 0, 5])
print("Test 1:\n", magic_square(test, f), "\n")
print("Test 2:\n", magic_square(test2, f), "\n")
print("Test 3:\n", magic_square(test3, f), "\n")
print("Test 4:\n", magic_square(test4, f))

Test 1:
 [[8 3 4]
 [1 5 9]
 [6 7 2]] 

Test 2:
 Geen oplossing: Oplossing bestaat niet uit integers 

Test 3:
 [[101   5  71]
 [ 29  59  89]
 [ 47 113  17]] 

Test 4:
 [[5 2 8]
 [8 5 2]
 [2 8 5]]
